name: Build and push docker image

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64, linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub as ${{ vars.DOCKERHUB_USERNAME }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_TAG }}

  wierd-voodoo:
    needs: build  # This ensures update-resource runs only after build completes
    runs-on: ubuntu-latest

    container:
      image: hiroregistry/juju-cd:latest  # Your pre-built Docker image with Juju

    env:
      JUJU_API_ENDPOINTS: ${{ secrets.JUJU_API_ENDPOINTS }}
      JUJU_RESOURCE_IMAGE: docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{  vars.DOCKERHUB_REPOSITORY }}:${{ github.ref_name == 'main' && 'latest' || 'dev' }}
      JUJU_APP_NAME: ${{ vars.JUJU_APP_NAME }}
      JUJU_RESOURCE_NAME: ${{ vars.JUJU_RESOURCE_NAME }}
      JUJU_CON: ${{ vars.JUJU_CONTROLLER }}
      JUJU_USERNAME: ${{ secrets.JUJU_USERNAME }}
      JUJU_PASSWORD: ${{ secrets.JUJU_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set JUJU_APP_NAME dynamically
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "JUJU_APP_NAME=${{ vars.JUJU_APP_NAME }}" >> $GITHUB_ENV
          else
            echo "JUJU_APP_NAME=${{ vars.JUJU_APP_NAME }}-dev" >> $GITHUB_ENV
          fi

      - name: Updating destination Model
        shell: bash
        run: |
          export HOME=/root
          /usr/local/bin/entrypoint.sh
          juju switch kubeflow
          echo "Switched to kubeflow model."
          echo "Attaching resource to Juju application..."
          echo juju attach-resource $JUJU_APP_NAME $JUJU_RESOURCE_NAME=$JUJU_RESOURCE_IMAGE
          juju attach-resource $JUJU_APP_NAME $JUJU_RESOURCE_NAME=$JUJU_RESOURCE_IMAGE
